import { IFakeFillerOptions, ICustomField } from "src/types";

// spell-checker:disable

const DEFAULT_TELEPHONE_TEMPLATE = "+91 XXXXXXXXXX";

export const CURRENT_SETTINGS_VERSION = 1;

export const DEFAULT_EMAIL_CUSTOM_FIELD: ICustomField = {
  type: "email",
  name: "Email Address",
  match: ["email"],
  emailPrefix: "",
  emailUsername: "random",
  emailUsernameList: ["jill", "juck"],
  emailUsernameRegEx: "",
  emailHostname: "list",
  emailHostnameList: ["example.com"],
};

const FakeFillerDefaultOptions = (): IFakeFillerOptions => {
  const options: IFakeFillerOptions = {
    version: CURRENT_SETTINGS_VERSION,
    agreeTermsFields: ["agree", "terms", "conditions"],
    confirmFields: ["confirm", "reenter", "retype", "repeat", "secondary"],
    defaultMaxLength: 20,
    enableContextMenu: true,
    fieldMatchSettings: {
      matchLabel: true,
      matchAriaLabel: true,
      matchAriaLabelledBy: true,
      matchId: true,
      matchName: true,
      matchClass: false,
      matchPlaceholder: false,
      customAttributes: [],
    },
    fields: [],
    ignoredFields: ["captcha", "hipinputtext"],
    ignoreFieldsWithContent: false,
    ignoreHiddenFields: true,
    passwordSettings: {
      mode: "defined",
      password: "Pa$$w0rd!",
    },
    profiles: [],
    triggerClickEvents: true,
    uploadFiles: true,
    urlMatchesToBlock: ["trello"],
  };

  options.fields.push({
    type: "username",
    name: "Username",
    match: ["userid", "username"],
  });

  options.fields.push({
    type: "first-name",
    name: "First Name",
    match: ["firstname", "givenname", "middlename"],
  });

  options.fields.push({
    type: "alphanumeric",
    name: "Middle Initial",
    match: ["initial"],
    template: "L",
  });

  options.fields.push({
    type: "last-name",
    name: "Last Name",
    match: ["lastname", "surname", "secondname", "familyname"],
  });

  options.fields.push({
    type: "randomized-list",
    name: "Suffix",
    match: ["suffix"],
    list: ["Sr", "Senior", "Sr.", "Junior", "Jr", "Jr.", "I", "II", "III", "IV"],
  });

  options.fields.push(DEFAULT_EMAIL_CUSTOM_FIELD);

  options.fields.push({
    type: "organization",
    name: "Organization or Company Name",
    match: ["organization", "organisation", "company"],
  });

  options.fields.push({
    type: "full-name",
    name: "Full Name",
    match: ["fullname", "name"],
  });

  options.fields.push({
    type: "regex",
    name: "Credit Card",
    match: ["creditcard"],
    template:
      // tslint:disable-next-line:max-line-length
      "((42){7}0|4000056655665550|5{12}4440|2223003122003220|520082{5}10|(510){5}0|378282246310005|371449635398431|6011(11|98)1{9}0|6011000990139420|3056930009020000|36227206271667|6555900000604100|3566002020360500|620{12}(4|0)0|620550{14}|(40{5}|5{6})2500001001|4000050360000001|5555050360000080)",
  });

  options.fields.push({
    type: "number",
    name: "Extension",
    match: ["extension"],
    min: 100,
    max: 999,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "telephone",
    name: "Telephone Number",
    match: ["phone", "fax", "mobile", "cell"],
    template: "+91 XXXXXXXXXX",
  });

  options.fields.push({
    type: "number",
    name: "A Random Number between 1 and 1000",
    match: ["integer", "number", "numeric", "income", "price", "qty", "quantity", "amount", "numof", "noof"],
    min: 1,
    max: 1000,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "number",
    name: "PIN Code",
    match: ["pin", "zip"],
    min: 100000,
    max: 999999,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "number",
    name: "Day",
    match: ["day"],
    min: 1,
    max: 28,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "number",
    name: "Month",
    match: ["month"],
    min: 1,
    max: 12,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "number",
    name: "Year",
    match: ["year"],
    min: 1970,
    max: 2022,
    decimalPlaces: 0,
  });

  options.fields.push({
    type: "date",
    name: "Date",
    match: ["date"],
    minDate: "1970-01-01",
    max: 0,
    template: "DD-MMM-YYYY",
  });

  options.fields.push({
    type: "url",
    name: "Website Address",
    match: ["website"],
  });

  options.fields.push({
    type: "regex",
    name: "Address Line 2",
    match: ["address2", "addressline2", "street2"],
    template: "(DoorNo|Suite|Apartment|Apt.?|#|Number|No|) [1-9][0-9]{0,2}[A-G]?",
  });

  options.fields.push({
    type: "regex",
    name: "Address Line 1",
    match: ["address", "street"],
    template:
      // tslint:disable-next-line:max-line-length
      "([1-9][0-9][0-9]?) (North |East |West |South |||||)(Green |White |Rocky ||||||||)(Nobel|Fabien|Hague|Oak|Second|First|Cowley|Clarendon|New|Old|Milton) (Avenue|Boulevard|Court|Drive|Extension|Freeway|Lane|Parkway|Road|Street)",
  });

  options.fields.push({
    type: "randomized-list",
    name: "City",
    match: ["city", "location"],
    list: [
      "Kolhapur",
      "Port Blair",
      "Adilabad",
      "Adoni",
      "Amadalavalasa",
      "Amalapuram",
      "Anakapalle",
      "Anantapur",
      "Badepalle",
      "Banganapalle",
      "Bapatla",
      "Bellampalle",
      "Bethamcherla",
      "Bhadrachalam",
      "Bhainsa",
      "Bheemunipatnam",
      "Bhimavaram",
      "Bhongir",
      "Bobbili",
      "Bodhan",
      "Chilakaluripet",
      "Chirala",
      "Chittoor",
      "Cuddapah",
      "Devarakonda",
      "Dharmavaram",
      "Eluru",
      "Farooqnagar",
      "Gadwal",
      "Gooty",
      "Gudivada",
      "Gudur",
      "Guntakal",
      "Guntur",
      "Hanuman Junction",
      "Hindupur",
      "Hyderabad",
      "Ichchapuram",
      "Jaggaiahpet",
      "Jagtial",
      "Jammalamadugu",
      "Jangaon",
      "Kadapa",
      "Kadiri",
      "Kagaznagar",
      "Kakinada",
      "Kalyandurg",
      "Kamareddy",
      "Kandukur",
      "Karimnagar",
      "Kavali",
      "Khammam",
      "Koratla",
      "Kothagudem",
      "Kothapeta",
      "Kovvur",
      "Kurnool",
      "Kyathampalle",
      "Macherla",
      "Machilipatnam",
      "Madanapalle",
      "Mahbubnagar",
      "Mancherial",
      "Mandamarri",
      "Mandapeta",
      "Manuguru",
      "Markapur",
      "Medak",
      "Miryalaguda",
      "Mogalthur",
      "Nagari",
      "Nagarkurnool",
      "Nandyal",
      "Narasapur",
      "Narasaraopet",
      "Narayanpet",
      "Narsipatnam",
      "Nellore",
      "Nidadavole",
      "Nirmal",
      "Nizamabad",
      "Nuzvid",
      "Ongole",
      "Palacole",
      "Palasa Kasibugga",
      "Palwancha",
      "Parvathipuram",
      "Pedana",
      "Peddapuram",
      "Pithapuram",
      "Pondur",
      "Ponnur",
      "Proddatur",
      "Punganur",
      "Puttur",
      "Rajahmundry",
      "Rajam",
      "Ramachandrapuram",
      "Ramagundam",
      "Rayachoti",
      "Rayadurg",
      "Renigunta",
      "Repalle",
      "Sadasivpet",
      "Salur",
      "Samalkot",
      "Sangareddy",
      "Sattenapalle",
      "Siddipet",
      "Singapur",
      "Sircilla",
      "Srikakulam",
      "Srikalahasti",
      "Suryapet",
      "Tadepalligudem",
      "Tadpatri",
      "Tandur",
      "Tanuku",
      "Tenali",
      "Tirupati",
      "Tuni",
      "Uravakonda",
      "Venkatagiri",
      "Vicarabad",
      "Vijayawada",
      "Vinukonda",
      "Visakhapatnam",
      "Vizianagaram",
      "Wanaparthy",
      "Warangal",
      "Yellandu",
      "Yemmiganur",
      "Yerraguntla",
      "Zahirabad",
      "Rajampet",
      "Along",
      "Bomdila",
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Abhayapuri",
      "Amguri",
      "Anandnagaar",
      "Barpeta",
      "Barpeta Road",
      "Bilasipara",
      "Bongaigaon",
      "Dhekiajuli",
      "Dhubri",
      "Dibrugarh",
      "Digboi",
      "Diphu",
      "Dispur",
      "Gauripur",
      "Goalpara",
      "Golaghat",
      "Guwahati",
      "Haflong",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Karimganj",
      "Kokrajhar",
      "Lanka",
      "Lumding",
      "Mangaldoi",
      "Mankachar",
      "Margherita",
      "Mariani",
      "Marigaon",
      "Nagaon",
      "Nalbari",
      "North Lakhimpur",
      "Rangia",
      "Sibsagar",
      "Silapathar",
      "Silchar",
      "Tezpur",
      "Tinsukia",
      "Amarpur",
      "Araria",
      "Areraj",
      "Arrah",
      "Asarganj",
      "Aurangabad",
      "Bagaha",
      "Bahadurganj",
      "Bairgania",
      "Bakhtiarpur",
      "Banka",
      "Banmankhi Bazar",
      "Barahiya",
      "Barauli",
      "Barbigha",
      "Barh",
      "Begusarai",
      "Behea",
      "Bettiah",
      "Bhabua",
      "Bhagalpur",
      "Bihar Sharif",
      "Bikramganj",
      "Bodh Gaya",
      "Buxar",
      "Chandan Bara",
      "Chanpatia",
      "Chhapra",
      "Colgong",
      "Dalsinghsarai",
      "Darbhanga",
      "Daudnagar",
      "Dehri-on-Sone",
      "Dhaka",
      "Dighwara",
      "Dumraon",
      "Fatwah",
      "Forbesganj",
      "Gaya",
      "Gogri Jamalpur",
      "Gopalganj",
      "Hajipur",
      "Hilsa",
      "Hisua",
      "Islampur",
      "Jagdispur",
      "Jamalpur",
      "Jamui",
      "Jehanabad",
      "Jhajha",
      "Jhanjharpur",
      "Jogabani",
      "Kanti",
      "Katihar",
      "Khagaria",
      "Kharagpur",
      "Kishanganj",
      "Lakhisarai",
      "Lalganj",
      "Madhepura",
      "Madhubani",
      "Maharajganj",
      "Mahnar Bazar",
      "Makhdumpur",
      "Maner",
      "Manihari",
      "Marhaura",
      "Masaurhi",
      "Mirganj",
      "Mokameh",
      "Motihari",
      "Motipur",
      "Munger",
      "Murliganj",
      "Muzaffarpur",
      "Narkatiaganj",
      "Naugachhia",
      "Nawada",
      "Nokha",
      "Patna",
      "Piro",
      "Purnia",
      "Rafiganj",
      "Rajgir",
      "Ramnagar",
      "Raxaul Bazar",
      "Revelganj",
      "Rosera",
      "Saharsa",
      "Samastipur",
      "Sasaram",
      "Sheikhpura",
      "Sheohar",
      "Sherghati",
      "Silao",
      "Sitamarhi",
      "Siwan",
      "Sonepur",
      "Sugauli",
      "Sultanganj",
      "Supaul",
      "Warisaliganj",
      "Ahiwara",
      "Akaltara",
      "Ambagarh Chowki",
      "Ambikapur",
      "Arang",
      "Bade Bacheli",
      "Balod",
      "Baloda Bazar",
      "Bemetra",
      "Bhatapara",
      "Bilaspur",
      "Birgaon",
      "Champa",
      "Chirmiri",
      "Dalli-Rajhara",
      "Dhamtari",
      "Dipka",
      "Dongargarh",
      "Durg-Bhilai Nagar",
      "Gobranawapara",
      "Jagdalpur",
      "Janjgir",
      "Jashpurnagar",
      "Kanker",
      "Kawardha",
      "Kondagaon",
      "Korba",
      "Mahasamund",
      "Mahendragarh",
      "Mungeli",
      "Naila Janjgir",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sakti",
      "Tilda Newra",
      "Amli",
      "Silvassa",
      "Daman and Diu",
      "Asola",
      "Delhi",
      "Aldona",
      "Curchorem Cacora",
      "Madgaon",
      "Mapusa",
      "Margao",
      "Marmagao",
      "Panaji",
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Ankleshwar",
      "Bharuch",
      "Bhavnagar",
      "Bhuj",
      "Cambay",
      "Dahod",
      "Deesa",
      "Dharampur",
      "Dholka",
      "Gandhinagar",
      "Godhra",
      "Himatnagar",
      "Idar",
      "Jamnagar",
      "Junagadh",
      "Kadi",
      "Kalavad",
      "Kalol",
      "Kapadvanj",
      "Karjan",
      "Keshod",
      "Khambhalia",
      "Khambhat",
      "Kheda",
      "Khedbrahma",
      "Kheralu",
      "Kodinar",
      "Lathi",
      "Limbdi",
      "Lunawada",
      "Mahesana",
      "Mahuva",
      "Manavadar",
      "Mandvi",
      "Mangrol",
      "Mansa",
      "Mehmedabad",
      "Modasa",
      "Morvi",
      "Nadiad",
      "Navsari",
      "Padra",
      "Palanpur",
      "Palitana",
      "Pardi",
      "Patan",
      "Petlad",
      "Porbandar",
      "Radhanpur",
      "Rajkot",
      "Rajpipla",
      "Rajula",
      "Ranavav",
      "Rapar",
      "Salaya",
      "Sanand",
      "Savarkundla",
      "Sidhpur",
      "Sihor",
      "Songadh",
      "Surat",
      "Talaja",
      "Thangadh",
      "Tharad",
      "Umbergaon",
      "Umreth",
      "Una",
      "Unjha",
      "Upleta",
      "Vadnagar",
      "Vadodara",
      "Valsad",
      "Vapi",
      "Veraval",
      "Vijapur",
      "Viramgam",
      "Visnagar",
      "Vyara",
      "Wadhwan",
      "Wankaner",
      "Adalaj",
      "Adityana",
      "Alang",
      "Ambaji",
      "Ambaliyasan",
      "Andada",
      "Anjar",
      "Anklav",
      "Antaliya",
      "Arambhada",
      "Atul",
      "Ballabhgarh",
      "Ambala",
      "Asankhurd",
      "Assandh",
      "Ateli",
      "Babiyal",
      "Bahadurgarh",
      "Barwala",
      "Bhiwani",
      "Charkhi Dadri",
      "Cheeka",
      "Ellenabad 2",
      "Faridabad",
      "Fatehabad",
      "Ganaur",
      "Gharaunda",
      "Gohana",
      "Gurgaon",
      "Haibat(Yamuna Nagar)",
      "Hansi",
      "Hisar",
      "Hodal",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Kalan Wali",
      "Kalka",
      "Karnal",
      "Ladwa",
      "Mandi Dabwali",
      "Narnaul",
      "Narwana",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Pehowa",
      "Pinjore",
      "Rania",
      "Ratia",
      "Rewari",
      "Rohtak",
      "Safidon",
      "Samalkha",
      "Shahbad",
      "Sirsa",
      "Sohna",
      "Sonipat",
      "Taraori",
      "Thanesar",
      "Tohana",
      "Yamunanagar",
      "Arki",
      "Baddi",
      "Bilaspur",
      "Chamba",
      "Dalhousie",
      "Dharamsala",
      "Hamirpur",
      "Mandi",
      "Nahan",
      "Shimla",
      "Solan",
      "Sundarnagar",
      "Jammu",
      "Achabbal",
      "Akhnoor",
      "Anantnag",
      "Arnia",
      "Awantipora",
      "Bandipore",
      "Baramula",
      "Kathua",
      "Leh",
      "Punch",
      "Rajauri",
      "Sopore",
      "Srinagar",
      "Udhampur",
      "Amlabad",
      "Ara",
      "Barughutu",
      "Bokaro Steel City",
      "Chaibasa",
      "Chakradharpur",
      "Chandrapura",
      "Chatra",
      "Chirkunda",
      "Churi",
      "Daltonganj",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "Garhwa",
      "Ghatshila",
      "Giridih",
      "Godda",
      "Gomoh",
      "Gumia",
      "Gumla",
      "Hazaribag",
      "Hussainabad",
      "Jamshedpur",
      "Jamtara",
      "Jhumri Tilaiya",
      "Khunti",
      "Lohardaga",
      "Madhupur",
      "Mihijam",
      "Musabani",
      "Pakaur",
      "Patratu",
      "Phusro",
      "Ramngarh",
      "Ranchi",
      "Sahibganj",
      "Saunda",
      "Simdega",
      "Tenu Dam-cum- Kathhara",
      "Arasikere",
      "Bangalore",
      "Belgaum",
      "Bellary",
      "Chamrajnagar",
      "Chikkaballapur",
      "Chintamani",
      "Chitradurga",
      "Gulbarga",
      "Gundlupet",
      "Hassan",
      "Hospet",
      "Hubli",
      "Karkala",
      "Karwar",
      "Kolar",
      "Kota",
      "Lakshmeshwar",
      "Lingsugur",
      "Maddur",
      "Madhugiri",
      "Madikeri",
      "Magadi",
      "Mahalingpur",
      "Malavalli",
      "Malur",
      "Mandya",
      "Mangalore",
      "Manvi",
      "Mudalgi",
      "Mudbidri",
      "Muddebihal",
      "Mudhol",
      "Mulbagal",
      "Mundargi",
      "Mysore",
      "Nanjangud",
      "Pavagada",
      "Puttur",
      "Rabkavi Banhatti",
      "Raichur",
      "Ramanagaram",
      "Ramdurg",
      "Ranibennur",
      "Robertson Pet",
      "Ron",
      "Sadalgi",
      "Sagar",
      "Sakleshpur",
      "Sandur",
      "Sankeshwar",
      "Saundatti-Yellamma",
      "Savanur",
      "Sedam",
      "Shahabad",
      "Shahpur",
      "Shiggaon",
      "Shikapur",
      "Shimoga",
      "Shorapur",
      "Shrirangapattana",
      "Sidlaghatta",
      "Sindgi",
      "Sindhnur",
      "Sira",
      "Sirsi",
      "Siruguppa",
      "Srinivaspur",
      "Talikota",
      "Tarikere",
      "Tekkalakota",
      "Terdal",
      "Tiptur",
      "Tumkur",
      "Udupi",
      "Vijayapura",
      "Wadi",
      "Yadgir",
      "Adoor",
      "Akathiyoor",
      "Alappuzha",
      "Ancharakandy",
      "Aroor",
      "Ashtamichira",
      "Attingal",
      "Avinissery",
      "Chalakudy",
      "Changanassery",
      "Chendamangalam",
      "Chengannur",
      "Cherthala",
      "Cheruthazham",
      "Chittur-Thathamangalam",
      "Chockli",
      "Erattupetta",
      "Guruvayoor",
      "Irinjalakuda",
      "Kadirur",
      "Kalliasseri",
      "Kalpetta",
      "Kanhangad",
      "Kanjikkuzhi",
      "Kannur",
      "Kasaragod",
      "Kayamkulam",
      "Kochi",
      "Kodungallur",
      "Kollam",
      "Koothuparamba",
      "Kothamangalam",
      "Kottayam",
      "Kozhikode",
      "Kunnamkulam",
      "Malappuram",
      "Mattannur",
      "Mavelikkara",
      "Mavoor",
      "Muvattupuzha",
      "Nedumangad",
      "Neyyattinkara",
      "Ottappalam",
      "Palai",
      "Palakkad",
      "Panniyannur",
      "Pappinisseri",
      "Paravoor",
      "Pathanamthitta",
      "Payyannur",
      "Peringathur",
      "Perinthalmanna",
      "Perumbavoor",
      "Ponnani",
      "Punalur",
      "Quilandy",
      "Shoranur",
      "Taliparamba",
      "Thiruvalla",
      "Thiruvananthapuram",
      "Thodupuzha",
      "Thrissur",
      "Tirur",
      "Vadakara",
      "Vaikom",
      "Varkala",
      "Kavaratti",
      "Ashok Nagar",
      "Balaghat",
      "Betul",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Dabra",
      "Datia",
      "Dewas",
      "Dhar",
      "Fatehabad",
      "Gwalior",
      "Indore",
      "Itarsi",
      "Jabalpur",
      "Katni",
      "Kotma",
      "Lahar",
      "Lundi",
      "Maharajpur",
      "Mahidpur",
      "Maihar",
      "Malajkhand",
      "Manasa",
      "Manawar",
      "Mandideep",
      "Mandla",
      "Mandsaur",
      "Mauganj",
      "Mhow Cantonment",
      "Mhowgaon",
      "Morena",
      "Multai",
      "Murwara",
      "Nagda",
      "Nainpur",
      "Narsinghgarh",
      "Neemuch",
      "Nepanagar",
      "Niwari",
      "Nowgong",
      "Nowrozabad",
      "Pachore",
      "Pali",
      "Panagar",
      "Pandhurna",
      "Panna",
      "Pasan",
      "Pipariya",
      "Pithampur",
      "Porsa",
      "Prithvipur",
      "Raghogarh-Vijaypur",
      "Rahatgarh",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rau",
      "Rehli",
      "Rewa",
      "Sabalgarh",
      "Sagar",
      "Sanawad",
      "Sarangpur",
      "Sarni",
      "Satna",
      "Sausar",
      "Sehore",
      "Sendhwa",
      "Seoni",
      "Seoni-Malwa",
      "Shahdol",
      "Shajapur",
      "Shamgarh",
      "Sheopur",
      "Shivpuri",
      "Shujalpur",
      "Sidhi",
      "Sihora",
      "Singrauli",
      "Sironj",
      "Sohagpur",
      "Tarana",
      "Tikamgarh",
      "Ujhani",
      "Ujjain",
      "Umaria",
      "Vidisha",
      "Wara Seoni",
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Baramati",
      "Chalisgaon",
      "Chinchani",
      "Devgarh",
      "Dhule",
      "Dombivli",
      "Durgapur",
      "Ichalkaranji",
      "Jalna",
      "Kalyan",
      "Latur",
      "Loha",
      "Lonar",
      "Lonavla",
      "Mahad",
      "Mahuli",
      "Malegaon",
      "Malkapur",
      "Manchar",
      "Mangalvedhe",
      "Mangrulpir",
      "Manjlegaon",
      "Manmad",
      "Manwath",
      "Mehkar",
      "Mhaswad",
      "Miraj",
      "Morshi",
      "Mukhed",
      "Mul",
      "Mumbai",
      "Murtijapur",
      "Nagpur",
      "Nalasopara",
      "Nanded-Waghala",
      "Nandgaon",
      "Nandura",
      "Nandurbar",
      "Narkhed",
      "Nashik",
      "Navi Mumbai",
      "Nawapur",
      "Nilanga",
      "Osmanabad",
      "Ozar",
      "Pachora",
      "Paithan",
      "Palghar",
      "Pandharkaoda",
      "Pandharpur",
      "Panvel",
      "Parbhani",
      "Parli",
      "Parola",
      "Partur",
      "Pathardi",
      "Pathri",
      "Patur",
      "Pauni",
      "Pen",
      "Phaltan",
      "Pulgaon",
      "Pune",
      "Purna",
      "Pusad",
      "Rahuri",
      "Rajura",
      "Ramtek",
      "Ratnagiri",
      "Raver",
      "Risod",
      "Sailu",
      "Sangamner",
      "Sangli",
      "Sangole",
      "Sasvad",
      "Satana",
      "Satara",
      "Savner",
      "Sawantwadi",
      "Shahade",
      "Shegaon",
      "Shendurjana",
      "Shirdi",
      "Shirpur-Warwade",
      "Shirur",
      "Shrigonda",
      "Shrirampur",
      "Sillod",
      "Sinnar",
      "Solapur",
      "Soyagaon",
      "Talegaon Dabhade",
      "Talode",
      "Tasgaon",
      "Tirora",
      "Tuljapur",
      "Tumsar",
      "Uran",
      "Uran Islampur",
      "Wadgaon Road",
      "Wai",
      "Wani",
      "Wardha",
      "Warora",
      "Warud",
      "Washim",
      "Yevla",
      "Uchgaon",
      "Udgir",
      "Umarga",
      "Umarkhed",
      "Umred",
      "Vadgaon Kasba",
      "Vaijapur",
      "Vasai",
      "Virar",
      "Vita",
      "Yavatmal",
      "Yawal",
      "Imphal",
      "Kakching",
      "Lilong",
      "Mayang Imphal",
      "Thoubal",
      "Jowai",
      "Nongstoin",
      "Shillong",
      "Tura",
      "Aizawl",
      "Champhai",
      "Lunglei",
      "Saiha",
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Anandapur",
      "Anugul",
      "Asika",
      "Balangir",
      "Balasore",
      "Baleshwar",
      "Bamra",
      "Barbil",
      "Bargarh",
      "Baripada",
      "Basudebpur",
      "Belpahar",
      "Bhadrak",
      "Bhawanipatna",
      "Bhuban",
      "Bhubaneswar",
      "Biramitrapur",
      "Brahmapur",
      "Brajrajnagar",
      "Byasanagar",
      "Cuttack",
      "Debagarh",
      "Dhenkanal",
      "Gunupur",
      "Hinjilicut",
      "Jagatsinghapur",
      "Jajapur",
      "Jaleswar",
      "Jatani",
      "Jeypur",
      "Jharsuguda",
      "Joda",
      "Kantabanji",
      "Karanjia",
      "Kendrapara",
      "Kendujhar",
      "Khordha",
      "Koraput",
      "Malkangiri",
      "Nabarangapur",
      "Paradip",
      "Parlakhemundi",
      "Pattamundai",
      "Phulabani",
      "Puri",
      "Rairangpur",
      "Rajagangapur",
      "Raurkela",
      "Rayagada",
      "Sambalpur",
      "Soro",
      "Sunabeda",
      "Sundargarh",
      "Talcher",
      "Titlagarh",
      "Umarkote",
      "Karaikal",
      "Mahe",
      "Pondicherry",
      "Yanam",
      "Ahmedgarh",
      "Amritsar",
      "Barnala",
      "Batala",
      "Bathinda",
      "Bhagha Purana",
      "Budhlada",
      "Chandigarh",
      "Dasua",
      "Dhuri",
      "Dinanagar",
      "Faridkot",
      "Fazilka",
      "Firozpur",
      "Firozpur Cantt.",
      "Giddarbaha",
      "Gobindgarh",
      "Gurdaspur",
      "Hoshiarpur",
      "Jagraon",
      "Jaitu",
      "Jalalabad",
      "Jalandhar",
      "Jalandhar Cantt.",
      "Jandiala",
      "Kapurthala",
      "Karoran",
      "Kartarpur",
      "Khanna",
      "Kharar",
      "Kot Kapura",
      "Kurali",
      "Longowal",
      "Ludhiana",
      "Malerkotla",
      "Malout",
      "Mansa",
      "Maur",
      "Moga",
      "Mohali",
      "Morinda",
      "Mukerian",
      "Muktsar",
      "Nabha",
      "Nakodar",
      "Nangal",
      "Nawanshahr",
      "Pathankot",
      "Patiala",
      "Patran",
      "Patti",
      "Phagwara",
      "Phillaur",
      "Qadian",
      "Raikot",
      "Rajpura",
      "Rampura Phul",
      "Rupnagar",
      "Samana",
      "Sangrur",
      "Sirhind Fatehgarh Sahib",
      "Sujanpur",
      "Sunam",
      "Talwara",
      "Tarn Taran",
      "Urmar Tanda",
      "Zira",
      "Zirakpur",
      "Bali",
      "Banswara",
      "Ajmer",
      "Alwar",
      "Bandikui",
      "Baran",
      "Barmer",
      "Bikaner",
      "Fatehpur",
      "Jaipur",
      "Jaisalmer",
      "Jodhpur",
      "Kota",
      "Lachhmangarh",
      "Ladnu",
      "Lakheri",
      "Lalsot",
      "Losal",
      "Makrana",
      "Malpura",
      "Mandalgarh",
      "Mandawa",
      "Mangrol",
      "Merta City",
      "Mount Abu",
      "Nadbai",
      "Nagar",
      "Nagaur",
      "Nargund",
      "Nasirabad",
      "Nathdwara",
      "Navalgund",
      "Nawalgarh",
      "Neem-Ka-Thana",
      "Nelamangala",
      "Nimbahera",
      "Nipani",
      "Niwai",
      "Nohar",
      "Nokha",
      "Pali",
      "Phalodi",
      "Phulera",
      "Pilani",
      "Pilibanga",
      "Pindwara",
      "Pipar City",
      "Prantij",
      "Pratapgarh",
      "Raisinghnagar",
      "Rajakhera",
      "Rajaldesar",
      "Rajgarh (Alwar)",
      "Rajgarh (Churu",
      "Rajsamand",
      "Ramganj Mandi",
      "Ramngarh",
      "Ratangarh",
      "Rawatbhata",
      "Rawatsar",
      "Reengus",
      "Sadri",
      "Sadulshahar",
      "Sagwara",
      "Sambhar",
      "Sanchore",
      "Sangaria",
      "Sardarshahar",
      "Sawai Madhopur",
      "Shahpura",
      "Sheoganj",
      "Sikar",
      "Sirohi",
      "Sojat",
      "Sri Madhopur",
      "Sujangarh",
      "Sumerpur",
      "Suratgarh",
      "Taranagar",
      "Todabhim",
      "Todaraisingh",
      "Tonk",
      "Udaipur",
      "Udaipurwati",
      "Vijainagar",
      "Gangtok",
      "Calcutta",
      "Arakkonam",
      "Arcot",
      "Aruppukkottai",
      "Bhavani",
      "Chengalpattu",
      "Chennai",
      "Chinna salem",
      "Coimbatore",
      "Coonoor",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Gudalur",
      "Kanchipuram",
      "Karaikudi",
      "Karungal",
      "Karur",
      "Kollankodu",
      "Lalgudi",
      "Madurai",
      "Nagapattinam",
      "Nagercoil",
      "Namagiripettai",
      "Namakkal",
      "Nandivaram-Guduvancheri",
      "Nanjikottai",
      "Natham",
      "Nellikuppam",
      "Neyveli",
      "O Valley",
      "Oddanchatram",
      "P.N.Patti",
      "Pacode",
      "Padmanabhapuram",
      "Palani",
      "Palladam",
      "Pallapatti",
      "Pallikonda",
      "Panagudi",
      "Panruti",
      "Paramakudi",
      "Parangipettai",
      "Pattukkottai",
      "Perambalur",
      "Peravurani",
      "Periyakulam",
      "Periyasemur",
      "Pernampattu",
      "Pollachi",
      "Polur",
      "Ponneri",
      "Pudukkottai",
      "Pudupattinam",
      "Puliyankudi",
      "Punjaipugalur",
      "Rajapalayam",
      "Ramanathapuram",
      "Rameshwaram",
      "Rasipuram",
      "Salem",
      "Sankarankoil",
      "Sankari",
      "Sathyamangalam",
      "Sattur",
      "Shenkottai",
      "Sholavandan",
      "Sholingur",
      "Sirkali",
      "Sivaganga",
      "Sivagiri",
      "Sivakasi",
      "Srivilliputhur",
      "Surandai",
      "Suriyampalayam",
      "Tenkasi",
      "Thammampatti",
      "Thanjavur",
      "Tharamangalam",
      "Tharangambadi",
      "Theni Allinagaram",
      "Thirumangalam",
      "Thirunindravur",
      "Thiruparappu",
      "Thirupuvanam",
      "Thiruthuraipoondi",
      "Thiruvallur",
      "Thiruvarur",
      "Thoothukudi",
      "Thuraiyur",
      "Tindivanam",
      "Tiruchendur",
      "Tiruchengode",
      "Tiruchirappalli",
      "Tirukalukundram",
      "Tirukkoyilur",
      "Tirunelveli",
      "Tirupathur",
      "Tiruppur",
      "Tiruttani",
      "Tiruvannamalai",
      "Tiruvethipuram",
      "Tittakudi",
      "Udhagamandalam",
      "Udumalaipettai",
      "Unnamalaikadai",
      "Usilampatti",
      "Uthamapalayam",
      "Uthiramerur",
      "Vadakkuvalliyur",
      "Vadalur",
      "Vadipatti",
      "Valparai",
      "Vandavasi",
      "Vaniyambadi",
      "Vedaranyam",
      "Vellakoil",
      "Vellore",
      "Vikramasingapuram",
      "Viluppuram",
      "Virudhachalam",
      "Virudhunagar",
      "Viswanatham",
      "Agartala",
      "Badharghat",
      "Dharmanagar",
      "Indranagar",
      "Jogendranagar",
      "Kailasahar",
      "Khowai",
      "Pratapgarh",
      "Udaipur",
      "Achhnera",
      "Adari",
      "Agra",
      "Aligarh",
      "Allahabad",
      "Amroha",
      "Azamgarh",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Bareilly",
      "Chandausi",
      "Dadri",
      "Deoria",
      "Etawah",
      "Fatehabad",
      "Fatehpur",
      "Greater Noida",
      "Hamirpur",
      "Hardoi",
      "Jajmau",
      "Jaunpur",
      "Jhansi",
      "Kalpi",
      "Kanpur",
      "Kota",
      "Laharpur",
      "Lakhimpur",
      "Lal Gopalganj Nindaura",
      "Lalganj",
      "Lalitpur",
      "Lar",
      "Loni",
      "Lucknow",
      "Mathura",
      "Meerut",
      "Modinagar",
      "Muradnagar",
      "Nagina",
      "Najibabad",
      "Nakur",
      "Nanpara",
      "Naraura",
      "Naugawan Sadat",
      "Nautanwa",
      "Nawabganj",
      "Nehtaur",
      "NOIDA",
      "Noorpur",
      "Obra",
      "Orai",
      "Padrauna",
      "Palia Kalan",
      "Parasi",
      "Phulpur",
      "Pihani",
      "Pilibhit",
      "Pilkhuwa",
      "Powayan",
      "Pukhrayan",
      "Puranpur",
      "Purquazi",
      "Purwa",
      "Rae Bareli",
      "Rampur",
      "Rampur Maniharan",
      "Rasra",
      "Rath",
      "Renukoot",
      "Reoti",
      "Robertsganj",
      "Rudauli",
      "Rudrapur",
      "Sadabad",
      "Safipur",
      "Saharanpur",
      "Sahaspur",
      "Sahaswan",
      "Sahawar",
      "Sahjanwa",
      "Saidpur",
      "Sambhal",
      "Samdhan",
      "Samthar",
      "Sandi",
      "Sandila",
      "Sardhana",
      "Seohara",
      "Shahabad",
      "Shahabad",
      "Shahganj",
      "Shahjahanpur",
      "Shamli",
      "Shamsabad",
      "Shamsabad",
      "Sherkot",
      "Shikarpur",
      "Shikohabad",
      "Shishgarh",
      "Siana",
      "Sikanderpur",
      "Sikandra Rao",
      "Sikandrabad",
      "Sirsaganj",
      "Sirsi",
      "Sitapur",
      "Soron",
      "Suar",
      "Sultanpur",
      "Sumerpur",
      "Tanda",
      "Tetri Bazar",
      "Thakurdwara",
      "Thana Bhawan",
      "Tilhar",
      "Tirwaganj",
      "Tulsipur",
      "Tundla",
      "Unnao",
      "Utraula",
      "Varanasi",
      "Vrindavan",
      "Warhapur",
      "Zaidpur",
      "Zamania",
      "Almora",
      "Bazpur",
      "Chamba",
      "Dehradun",
      "Haldwani",
      "Haridwar",
      "Jaspur",
      "Kashipur",
      "kichha",
      "Kotdwara",
      "Manglaur",
      "Mussoorie",
      "Nagla",
      "Nainital",
      "Pauri",
      "Pithoragarh",
      "Ramnagar",
      "Rishikesh",
      "Roorkee",
      "Rudrapur",
      "Sitarganj",
      "Tehri",
      "Muzaffarnagar",
      "Adra",
      "Alipurduar",
      "Arambagh",
      "Asansol",
      "Baharampur",
      "Bally",
      "Balurghat",
      "Bankura",
      "Barakar",
      "Barasat",
      "Bardhaman",
      "Bidhan Nagar",
      "Chinsura",
      "Contai",
      "Cooch Behar",
      "Darjeeling",
      "Durgapur",
      "Haldia",
      "Howrah",
      "Islampur",
      "Jhargram",
      "Kharagpur",
      "Kolkata",
      "Mainaguri",
      "Mal",
      "Mathabhanga",
      "Medinipur",
      "Memari",
      "Monoharpur",
      "Murshidabad",
      "Nabadwip",
      "Naihati",
      "Panchla",
      "Pandua",
      "Paschim Punropara",
      "Purulia",
      "Raghunathpur",
      "Raiganj",
      "Rampurhat",
      "Ranaghat",
      "Sainthia",
      "Santipur",
      "Siliguri",
      "Sonamukhi",
      "Srirampore",
      "Suri",
      "Taki",
      "Tamluk",
      "Tarakeswar",
      "Chikmagalur",
      "Davanagere",
      "Dharwad",
      "Gadag",
    ],
  });

  options.fields.push({
    type: "regex",
    name: "P.O. Box",
    match: ["pobox", "postoffice", "postbox", "postofficebox"],
    template: "((P\\.O\\.)|(PO)) Box [1-9][0-9]{0,4}",
  });

  return options;
};

const GetFakeFillerOptions = (): Promise<IFakeFillerOptions> => {
  const promise = new Promise<IFakeFillerOptions>((resolve) => {
    chrome.storage.local.get("options", (result) => {
      let options: IFakeFillerOptions;
      if (result && Object.keys(result).length > 0) {
        options = result.options;
      } else {
        options = FakeFillerDefaultOptions();
      }
      resolve(options);
    });
  });

  return promise;
};

const CreateContextMenus = (enableContextMenu: boolean): void => {
  chrome.contextMenus.removeAll();

  if (enableContextMenu) {
    chrome.contextMenus.create({
      id: "fake-filler-all",
      title: "Fill all inputs",
      contexts: ["page", "editable"],
    });

    chrome.contextMenus.create({
      id: "fake-filler-form",
      title: "Fill this form",
      contexts: ["editable"],
    });

    chrome.contextMenus.create({
      id: "fake-filler-input",
      title: "Fill this input",
      contexts: ["editable"],
    });
  }
};

const SaveFakeFillerOptions = (options: IFakeFillerOptions): void => {
  chrome.storage.local.set({
    options,
  });

  chrome.runtime.sendMessage({ type: "optionsUpdated", data: options }, () => chrome.runtime.lastError);
  CreateContextMenus(options.enableContextMenu);
};

const SanitizeText = (text: string): string => {
  return text.replace(/[^a-zA-Z0-9]+/g, "").toLowerCase();
};

const CsvToArray = (csvString: string, sanitize = false): string[] => {
  const splitValues = csvString && csvString.length > 0 ? csvString.split(",") : [];
  const arrayData: string[] = [];

  for (let i = 0; i < splitValues.length; i += 1) {
    splitValues[i] = splitValues[i].replace(/^\s*/, "").replace(/\s*$/, "");

    if (sanitize) {
      splitValues[i] = SanitizeText(splitValues[i]);
    }

    if (splitValues[i].length > 0) {
      arrayData.push(splitValues[i]);
    }
  }

  return arrayData;
};

const MultipleLinesToArray = (text: string): string[] => {
  const splitValues = text && text.length > 0 ? text.split("\n") : [];
  const arrayData: string[] = [];

  for (let i = 0; i < splitValues.length; i += 1) {
    splitValues[i] = splitValues[i].replace(/^\s*/, "").replace(/\s*$/, "");
    if (splitValues[i].length > 0) {
      arrayData.push(splitValues[i]);
    }
  }

  return arrayData;
};

const GetKeyboardShortcuts = (): Promise<chrome.commands.Command[]> => {
  const promise = new Promise<chrome.commands.Command[]>((resolve) => {
    chrome.commands.getAll((result) => {
      resolve(result);
    });
  });

  return promise;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const GetMessage = (key: string, parameters?: any): string => {
  return chrome.i18n.getMessage(key, parameters);
};

export {
  DEFAULT_TELEPHONE_TEMPLATE,
  CreateContextMenus,
  CsvToArray,
  FakeFillerDefaultOptions,
  GetFakeFillerOptions,
  GetKeyboardShortcuts,
  GetMessage,
  MultipleLinesToArray,
  SanitizeText,
  SaveFakeFillerOptions,
};
